# Generated by Django 2.2.4 on 2019-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='title',
            field=models.CharField(default='0000000', editable=False, max_length=10),
        ),
    ]
