# Generated by Django 2.2.4 on 2019-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_userimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='d',
            field=models.CharField(default='0', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
