# Generated by Django 2.2.4 on 2019-09-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20190901_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
