# Generated by Django 2.2.4 on 2019-09-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='title',
        ),
    ]
