# Generated by Django 2.2.4 on 2019-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_auto_20190903_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\billy\\Desktop\\Projects\\Python\\Django\\UploadDetect\\media'),
        ),
    ]
