# Generated by Django 2.2.4 on 2019-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_auto_20190905_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\billy\\Desktop\\Projects\\Python\\Django\\UploadDetect\\media/'),
        ),
    ]
