# Generated by Django 2.2.5 on 2019-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_auto_20190906_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\billy\\Desktop\\Projects\\Python\\Django\\UploadDetect\\media//uploader/'),
        ),
    ]
