# Generated by Django 2.2.4 on 2019-09-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_image', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\billy\\Desktop\\Projects\\Python\\Django\\UploadDetect\\media/images')),
            ],
        ),
    ]
