# Generated by Django 2.2.4 on 2019-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiedimage',
            name='modified_image',
            field=models.ImageField(blank=True, null=True, upload_to='modified'),
        ),
    ]
